version: '4'

services:
  mosquitto:
    container_name: cow-mqtt
    image: eclipse-mosquitto:2.0.15
    restart: always
    volumes:
    - ./config:/mosquitto/config
    - ./config:/mosquitto/data
    - ./config:/mosquitto/log
    ports:
    - 1883:1883
    - 9001:9001
